### ISSUE TITLE
Mouse accuracy on OSX

### ISSUE THREAD

**Issue by jherman3** [apessino/modulator_play#2]
Running this on OSX gives an inaccurate mouse cursor (see GIF). I've experienced similar issues with OpenGL Rust programs and it was due to not scaling the mouse coordinates for HiDPI. 
Here's the bug:
![glitch](https://user-images.githubusercontent.com/7232353/48923615-25119780-ee7e-11e8-8945-f2855ed4d812.gif)

**Comment by apessino** [comment]
Interesting... I am just reading the mouse location from the Piston event, I am guessing the problem is down at the platform support layer - might have to ask the Piston guys. I will have to look into this, but I don't have immediate access to a Mac so it might take a while. If you feel like digging a bit into the guts of Piston feel free to let me know what you find. :D 

Thanks!

**Comment by xTibor** [comment]
Doesn't seem to be Mac specific, it's reproducible on my Linux desktop too. (KDE neon 5.14 / Ubuntu 18.04)

**Comment by apessino** [comment]
Thanks for the info - can't say that I have immediate access to that either. So if you find out anything more please let me know. :) I will chat with the Piston devs next week and see if they can point me in the right direction.

**Comment by apessino** [comment]
Found the scaling factor from glutin window, added it. Seems to be fixed.

Thanks!
